import os
from django.db import models
from django.utils.text import slugify
import google.generativeai as genai
from django.utils.text import slugify
from django.utils import timezone


class Category(models.Model):
    name = models.CharField(max_length=100, unique=True)
    slug = models.SlugField(unique=True, blank=True)

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.name)
        super().save(*args, **kwargs)

    def __str__(self):
        return self.name

class Content(models.Model):
    LANGUAGES = [('Hindi', 'Hindi'), ('English', 'English'), ('Hinglish', 'Hinglish')]
    
    title = models.CharField(max_length=200)
    video = models.FileField(upload_to='videos/')
    video_url = models.URLField(blank=True, null=True, max_length=500)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    language = models.CharField(max_length=50, choices=LANGUAGES, default="Hindi")
    
    # Algorithm Fields
    views = models.PositiveIntegerField(default=0)
    likes = models.PositiveIntegerField(default=0)
    shares = models.PositiveIntegerField(default=0)
    rank_score = models.IntegerField(default=0) # Simple Algorithm
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-rank_score', '-created_at']

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        if self.video and not self.video_url:
            self.video_url = self.video.url
            # update_fields use karne se recursion nahi hoga
            Content.objects.filter(id=self.id).update(video_url=self.video.url)


class Content(models.Model):
    LANGUAGE_CHOICES = [
        ('Hindi', 'Hindi'),
        ('English', 'English'),
        ('Hinglish', 'Hinglish'),
    ]

    title = models.CharField(max_length=200)
    video = models.FileField(upload_to='videos/')  
    video_url = models.URLField(blank=True, null=True, max_length=500)
    thumbnail = models.ImageField(upload_to='thumbnails/', blank=True, null=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    language = models.CharField(max_length=50, choices=LANGUAGE_CHOICES, default="Hindi")
    
    # AI Automatic Fields (Generated by Gemini)
    description = models.TextField(blank=True, help_text="AI automatically writes this on upload")
    has_quiz = models.BooleanField(default=False)
    quiz_question = models.CharField(max_length=255, blank=True, null=True)
    option_a = models.CharField(max_length=100, blank=True, null=True)
    option_b = models.CharField(max_length=100, blank=True, null=True)
    correct_option = models.CharField(max_length=1, choices=[('A', 'Option A'), ('B', 'Option B')], blank=True, null=True)
    
    # Engagement Analytics Engine
    views = models.PositiveIntegerField(default=0)
    likes = models.PositiveIntegerField(default=0)
    shares = models.PositiveIntegerField(default=0)
    watch_time_score = models.IntegerField(default=0)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-watch_time_score', '-created_at']

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        is_new = self.pk is None
        super().save(*args, **kwargs)
        
        # 1. Local URL management update
        if self.video and not self.video_url:
            self.video_url = self.video.url
            super().save(update_fields=['video_url'])
            
        # 2. AI Auto-Description & Quiz Generator Pipeline
        if is_new and self.video:
            try:
                self.generate_ai_metadata()
            except Exception as e:
                print(f"AI Extraction failed, falling back safely: {e}")


    def generate_ai_metadata(self):
        """
        Connects with Legacy Gemini Client API to process the generated learning item 
        and updates the summary description cards dynamically (Python 3.8 Compatible).
        """
        api_key = os.environ.get("GEMINI_API_KEY", "YOUR_GEMINI_API_KEY_HERE")
        
        if api_key == "YOUR_GEMINI_API_KEY_HERE":
            self.description = f"Smart tutorial about {self.title}. Learn more on #ScrollGuru!"
            super().save(update_fields=['description'])
            return

        # Configure the legacy library
        genai.configure(api_key=api_key)
        model = genai.GenerativeModel('gemini-1.5-flash') # Highly optimized for speed & text generation
        
        prompt = f"""
        You are an expert AI writer for ScrollGuru (an educational reels app). 
        Analyze this educational item title: '{self.title}' inside the category '{self.category.name}'.
        
        Generate exactly 2 things in clear text format separated by '---':
        1. An catchy, addictive 1-line short summary card with 2 relevant hashtags (Max 80 characters).
        2. A simple multiple-choice revision quiz question with two options (A and B) and tell which one is correct.
        
        Format output strictly exactly like this template:
        DESCRIPTION: Your 1-line summary here #tag1 #tag2
        ---
        QUESTION: Your question here?
        A: Option A text
        B: Option B text
        CORRECT: A
        """

        response = model.generate_content(prompt)
        ai_response_text = response.text
        
        # Parse text chunks cleanly
        # Inside your Content class's generate_ai_metadata() under models.py, change the try block parsing logic to this:
        try:
            parts = ai_response_text.split('---')
            desc_part = parts[0].replace("DESCRIPTION:", "").strip()
            quiz_part = parts[1].strip()
            
            lines = [line.strip() for line in quiz_part.split('\n') if line.strip()]
            q_text = lines[0].replace("QUESTION:", "").strip()
            a_text = lines[1].replace("A:", "").strip()
            b_text = lines[2].replace("B:", "").strip()
            correct_val = lines[3].replace("CORRECT:", "").strip()
            
            self.description = desc_part
            self.has_quiz = True
            self.quiz_question = q_text
            self.option_a = a_text
            self.option_b = b_text
            self.correct_option = correct_val
            
            super().save(update_fields=['description', 'has_quiz', 'quiz_question', 'option_a', 'option_b', 'correct_option'])
        except Exception as parse_error:
            self.description = f"Learn how to master {self.title} step by step! 🚀 #{self.category.slug}"
            super().save(update_fields=['description'])


class UserStreak(models.Model):
    session_key = models.CharField(max_length=100, unique=True)
    current_streak = models.PositiveIntegerField(default=0)
    longest_streak = models.PositiveIntegerField(default=0)
    last_login_date = models.DateField(auto_now=True)
    total_xp_earned = models.PositiveIntegerField(default=0)
    last_reward_claimed = models.DateField(null=True, blank=True)

    def __str__(self):
        return f"Streak {self.current_streak} - {self.session_key[:8]}"


class Follow(models.Model):
    follower = models.ForeignKey('accounts.CustomUser', on_delete=models.CASCADE, related_name='following')
    following = models.ForeignKey('accounts.CustomUser', on_delete=models.CASCADE, related_name='followers')
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        unique_together = ('follower', 'following')

    def __str__(self):
        return f"{self.follower} follows {self.following}"
    

class Story(models.Model):
    user = models.ForeignKey('accounts.CustomUser', on_delete=models.CASCADE, related_name='stories')
    video = models.FileField(upload_to='stories/')
    caption = models.CharField(max_length=150, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    expires_at = models.DateTimeField()

    def save(self, *args, **kwargs):
        if not self.expires_at:
            self.expires_at = timezone.now() + timezone.timedelta(hours=24)
        super().save(*args, **kwargs)

    def is_expired(self):
        return timezone.now() > self.expires_at

    class Meta:
        ordering = ['-created_at']