# Generated by Django 4.2.30 on 2026-05-28 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("slug", models.SlugField(blank=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="UserStreak",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_key", models.CharField(max_length=100, unique=True)),
                ("current_streak", models.PositiveIntegerField(default=0)),
                ("longest_streak", models.PositiveIntegerField(default=0)),
                ("last_login_date", models.DateField(auto_now=True)),
                ("total_xp_earned", models.PositiveIntegerField(default=0)),
                ("last_reward_claimed", models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Content",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("video", models.FileField(upload_to="videos/")),
                ("video_url", models.URLField(blank=True, max_length=500, null=True)),
                (
                    "thumbnail",
                    models.ImageField(blank=True, null=True, upload_to="thumbnails/"),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("Hindi", "Hindi"),
                            ("English", "English"),
                            ("Hinglish", "Hinglish"),
                        ],
                        default="Hindi",
                        max_length=50,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="AI automatically writes this on upload"
                    ),
                ),
                ("has_quiz", models.BooleanField(default=False)),
                (
                    "quiz_question",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("option_a", models.CharField(blank=True, max_length=100, null=True)),
                ("option_b", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "correct_option",
                    models.CharField(
                        blank=True,
                        choices=[("A", "Option A"), ("B", "Option B")],
                        max_length=1,
                        null=True,
                    ),
                ),
                ("views", models.PositiveIntegerField(default=0)),
                ("likes", models.PositiveIntegerField(default=0)),
                ("shares", models.PositiveIntegerField(default=0)),
                ("watch_time_score", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="content.category",
                    ),
                ),
            ],
            options={
                "ordering": ["-watch_time_score", "-created_at"],
            },
        ),
    ]
